name: setup-env
description: Setup Environment

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x

    - name: Print .NET version and SDKs
      shell: bash
      run: |
        dotnet --version
        dotnet --list-sdks
