on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build solution
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: dotnet build -c Release
  test:
    runs-on: ubuntu-latest
    name: Test solution
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: ./test.sh