on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build solution
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: dotnet build -c Release
  test:
    runs-on: ubuntu-latest
    name: Test solution
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: ./test.sh
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && success()
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: ./publish-packages.sh "https://api.nuget.org/v3/index.json" ${{ secrets.NUGET_KEY }} "$TRAVIS_TAG"