on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: ./publish-packages.sh "https://api.nuget.org/v3/index.json" ${{ secrets.NUGET_KEY }} ${{ env.RELEASE_VERSION }}